[project]
name = "local-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "faster-whisper>=1.2.1",
    "ollama>=0.6.2",
    "pillow>=12.2.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.49.0",
]
